### ISSUE TITLE
Lift Machine is stealing from its children

### ISSUE THREAD

**Issue by dpp** [lift/framework#1007]
Hello! I hope things are well with you.  I have been trying to compile
lift with RC3 and I ran into something hard to figure out in
lift-modules, so I enclose my findings.

You have some code along these lines.  (The code below compiles in 2.8.1.)

trait MetaProtoStateMachine [MyType <: ProtoStateMachine[MyType,
StateType], StateType <: Enumeration]
extends ProtoStateMachine[MyType, StateType] {
 self: MyType =>

 protected def processEvent(who: MyType, x: Int) {
   getSingleton.processEvent(this, x)
 }
}

trait ProtoStateMachine[MyType <: ProtoStateMachine[MyType, StateType],
StateType <: Enumeration] {
 self: MyType =>

 type Meta = MetaProtoStateMachine[MyType, StateType]
 def getSingleton: Meta

 def processEvent(x: Int): Unit = {
   getSingleton.processEvent(this, x)
 }
}

This only compiled in 2.8.1 due to a bug, which has been fixed.

 https://lampsvn.epfl.ch/trac/scala/ticket/3871

The error message is extremely confusing due to the overload: because
there is a method with the same name which is accessible, it assumes you
gave the wrong number of arguments and doesn't tell you that the
protected one was inaccessible.  I intend to open a ticket about the
error message.

The confusing error is:

./a.scala:17: error: too many arguments for method processEvent: (x:
Int)Unit
   getSingleton.processEvent(this, x)
                            ^
one error found

But if we rename the 2-argument method to processEvent2 and leave the
other alone, we get the less confusing error:

./a.scala:17: error: method processEvent2 in trait MetaProtoStateMachine
cannot be accessed in ProtoStateMachine.this.Meta
 Access to protected method processEvent2 not permitted because
 enclosing class trait ProtoStateMachine is not a subclass of
 trait MetaProtoStateMachine where target is defined
   getSingleton.processEvent2(this, x)
                ^
one error found

Superclass can't access protected members of subclass, even from the
same instance.  It's like stealing from your children!
